return {
  -- "MeanderingProgrammer/markdown.nvim",
  -- opts = {
  --   heading = {
  --     width = "block",
  --     -- The 'level' is used to index into the array using a clamp
  --     -- Highlight for the heading icon and extends through the entire line
  --     backgrounds = {
  --       "RenderMarkdownH1Bg",
  --       "RenderMarkdownH2Bg",
  --       "RenderMarkdownH3Bg",
  --       "RenderMarkdownH4Bg",
  --       "RenderMarkdownH5Bg",
  --       "RenderMarkdownH6Bg",
  --     },
  --   },
  --   code = {
  --     -- Highlight for code blocks
  --     highlight = "RenderMarkdownCode",
  --     -- Highlight for inline code
  --     highlight_inline = "RenderMarkdownCodeInline",
  --   },
  -- },
}
